# Generated by Django 5.2.6 on 2025-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drescricao', models.CharField(max_length=150)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser feito'), ('pode ser adiado', 'Pode ser adiado')], default='importante', max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
            ],
        ),
    ]
