# Generated by Django 5.2.6 on 2025-09-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veloizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='drescricao',
            new_name='descricao',
        ),
    ]
