# Generated by Django 5.2.6 on 2025-09-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloizapp', '0002_rename_drescricao_tarefa_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='dataCriacao',
            new_name='data_criacao',
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(max_length=1500)),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='veloizapp.tarefa')),
            ],
            options={
                'ordering': ['-data_comentario'],
            },
        ),
    ]
