# Generated by Django 5.2.6 on 2025-10-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veloizapp', '0004_tarefa_responsavel_alter_tarefa_status_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('pessoal', 'Pessoal'), ('trabalho', 'Trabalho'), ('estudos', 'Estudos'), ('saude', 'Saúde'), ('financas', 'Finanças'), ('outro', 'Outro')], default='pessoal', max_length=20),
        ),
    ]
